"""
CLI-layer compatibility freeze for `--hunt` (v2.4 output migration, PR4 --
the CLI's atomic switch onto the v2.4 `--hunt` contract) -- runs the real
`cli.main()` end to end against a synthetic `FakeMF`, the same discipline
tests/integration/test_report_compat_freeze.py established for the prior
(`--report`) migration: monkeypatch `cli.open_dump()` to return the fake
(no real .dmp file is parsed), freeze `datetime.datetime.now()` so
`meta.execution.started_at/finished_at/duration_seconds` are reproducible,
and assert exit code + full JSON `HunterRecord` + full CSV text + full
console body. Every module-attribute override (`read_region`/
`get_thread_contexts`) goes through pytest's `monkeypatch` fixture, never a
bare module-attribute assignment -- nothing here can leak into a later,
unrelated test regardless of execution order.

Every scenario (one per hunter, plus `stomping_ioc_hit`/`cs-beacon_multi`
as second scenarios for those two hunters -- see
tests/fixtures/hunt_cli_scenarios.py's own docstring for why) is defined
ONCE in tests/fixtures/hunt_cli_scenarios.py's `SCENARIOS` table and run
here BOTH normal and `--verbose` via `test_hunt_scenario_cli`'s own
parametrization -- not two independent, hand-copied test functions per
scenario. `scripts/update_hunt_cli_goldens.py` iterates the exact same
`SCENARIOS` table (and the exact same tests/fixtures/hunt_cli_harness.py
`run_cli()`/`split_console_body()`) to regenerate the golden fixtures this
file diffs against, so the "thing that produces the golden" and "thing
that checks against it" can never independently drift the way two
hand-copied fixture constructions could.

6 of the 9 scenarios (injection/hollowing/stomping[+ioc_hit]/pipe/
cs-beacon[+multi]/obfuscation) render `--verbose` via the shared
`Finding.print(verbose=..., facts_mode=...)` machinery; `yara` does NOT
share that model (see tests/hunt/test_finding_invariants.py's own
docstring) and has its own, independent --verbose branch in
`dumpex/hunt/yara_hunt/presentation.py`'s `render_result()` -- its
scenario is still driven through the same parametrized test, just gated
behind `pytest.importorskip("yara")` via `HuntCliScenario.needs_yara`.

tests/fixtures/hunt_cases.py + tests/integration/test_hunt_compat_freeze.py
freeze each hunter's OWN `_hunt_*()`/`cmd_hunt()` v1.1-shaped dict return
value in isolation (no CLI, no `meta`) -- that contract is UNCHANGED by
PR4 (see cmd_hunt()'s own docstring: its console output and bare `results`
dict return value are byte-identical to before; only the CLI's own
`--json`/`--csv` output and process exit code moved onto the v2.4
envelope). This file freezes what that approach cannot: what
`dumpex.output.V2Output` actually writes to `--json`/`--csv` for `--hunt`
now, and the real process exit code -- now coverage-based via
`exit_code_for()`, the same convention the ten other v2-routed commands
already used, rather than always 0 regardless of coverage.

Expected values live in tests/fixtures/hunt_cli_golden/<name>_{hunt_dict.json,
csv.txt,console.txt}, where <name> is the scenario's own name (see
`SCENARIOS` above -- usually the hunter's own <ttp>, but not always, for
the two hunters with a second scenario). `--verbose` never changes
`hunt_dict.json`/`csv.txt` (Finding.print()'s `verbose`/`facts_mode`
parameters, and yara_hunt's own independent verbose branch, only ever
change what presentation.py prints, never the JSON/CSV wire contract --
see Finding.print()'s own docstring), so those two files are shared
between a scenario's normal and `--verbose` run; only the console fixture
(`<name>_console.txt` vs. `<name>_verbose_console.txt`) differs. These are
NOT real-dump output (see tests/fixtures/hunt_cases.py's own docstring for
why that would be a privacy violation) -- every one of them was produced
by exactly the FakeMF construction `SCENARIOS` builds, so re-running
`scripts/update_hunt_cli_goldens.py` against the same construction
reproduces them byte-for-byte. Historical note: `<ttp>_console.txt` was
unchanged from the pre-PR4 (v1.1) fixtures at the time PR4 (the v2.4
output migration this file's own name refers to) landed, since
`cmd_hunt()`'s console rendering wasn't touched by THAT switch -- it has
since been regenerated by the console-standardization work that
introduced Finding.print()'s `verbose`/`facts_mode` parameters, so that
byte-identity claim no longer holds; this file's PURPOSE (freezing the
`--json`/`--csv`/exit-code wire contract PR4 introduced) is unaffected
either way.

Like test_report_compat_freeze.py, this does NOT compare the full JSON
document as one string -- `meta.evidence.path` embeds `tmp_path` (different
every test run) and `meta.tool.version` embeds this checkout's git-describe
string, neither of which a frozen fixture can pin. Only
`doc["result"]["data"]["records"][0]` (the single `HunterRecord` dict for
a single-TTP run -- the part with no such dynamic content) is compared, in
full; `test_hunt_all_all_not_evaluated` compares the full 7-element
`records` list the same way.

`test_hunt_all_all_not_evaluated`, like every scenario in `SCENARIOS`,
freezes the FULL JSON `records` list (all 7 hunters at once)/CSV/console
body -- it does NOT rely on the default packaged YARA rules directory
(which would print its own absolute host path, an un-freezable dynamic
segment): it passes `--yara-dir <tmp_path>/empty_rules` (a synthetic,
always-empty directory), same as `SCENARIOS["yara"]` passes its own
`tmp_path`-derived rules dir. Both have that one dynamic path segment
replaced with the literal placeholder `<RULES_DIR>` before comparison.
Requires no optional yara-python dependency either way: an empty rules
directory hits yara_hunt's "no .yar/.yara files found" branch before ever
importing it (see `SCENARIOS["yara"].needs_yara` for the one scenario that
actually needs a compiled rule and does need it).

Global rules-loader state and per-run datetime freezing are handled by
tests/fixtures/hunt_cli_harness.py's `run_cli()` -- see that module's own
docstring for why it's a shared helper rather than copied into this file
and the golden-update script independently.
"""
import json
import pathlib

import pytest

import dumpex.cli as cli

from tests.fixtures.hunt_cli_harness import run_cli, split_console_body, normalize_object_addresses
from tests.fixtures.hunt_cli_scenarios import SCENARIOS

_GOLDEN = pathlib.Path(__file__).parent.parent / "fixtures" / "hunt_cli_golden"


def _load_golden(name, console_variant="console"):
    """`console_variant` selects which `<name>_<variant>.txt` fixture to
    read for the console body -- "console" (default, --verbose NOT passed)
    or "verbose_console" (--verbose passed). The JSON record and CSV text
    are never --verbose-sensitive (see this module's own docstring), so
    `<name>_hunt_dict.json`/`<name>_csv.txt` are shared by both variants;
    only the console fixture differs."""
    hunt_dict = json.loads((_GOLDEN / f"{name}_hunt_dict.json").read_text(encoding="utf-8"))
    csv_text = (_GOLDEN / f"{name}_csv.txt").read_text(encoding="utf-8")
    console = (_GOLDEN / f"{name}_{console_variant}.txt").read_text(encoding="utf-8")
    return hunt_dict, csv_text, console


def _assert_frozen(name, doc, csv_text, body, *, console_variant="console"):
    """`body` is the ALREADY split (split_console_body) and, if applicable,
    rules-dir-substituted console text -- the exact string a scenario's
    `extra_checks` also receives, so both see identical content."""
    expected_record, expected_csv, expected_console = _load_golden(name, console_variant)
    records = doc["result"]["data"]["records"]
    assert len(records) == 1, f"expected exactly 1 record for a single-TTP run, got {len(records)}"
    assert normalize_object_addresses(records[0]) == expected_record
    assert csv_text == expected_csv
    assert body == expected_console


@pytest.mark.parametrize("verbose", [False, True], ids=["normal", "verbose"])
@pytest.mark.parametrize("scenario_name", list(SCENARIOS))
def test_hunt_scenario_cli(monkeypatch, tmp_path, scenario_name, verbose):
    scenario = SCENARIOS[scenario_name]
    if scenario.needs_yara:
        pytest.importorskip("yara")   # scoped to this parametrization only --
                                       # every non-yara scenario must still run
                                       # in an environment without the optional
                                       # yara-python ("full") extra installed.

    built = scenario.build(monkeypatch, tmp_path)
    argv = ["--hunt", scenario.ttp, *built.extra_argv]
    if verbose:
        argv.append("--verbose")

    exit_code, doc, csv_text, console = run_cli(monkeypatch, tmp_path, argv, built.mf)
    # Exit code isn't captured in any golden fixture -- asserted for every
    # scenario (not only ones with extra_checks) so a regression that
    # silently changes it can't slip past both this and --check with zero
    # diff anywhere. See HuntCliScenario.expected_exit_code's own docstring.
    assert exit_code == scenario.expected_exit_code, (
        f"{scenario_name} ({'verbose' if verbose else 'normal'}): expected exit code "
        f"{scenario.expected_exit_code}, got {exit_code}")

    body = split_console_body(console)
    if built.rules_dir is not None:
        body = body.replace(str(built.rules_dir), "<RULES_DIR>")

    if scenario.extra_checks is not None:
        scenario.extra_checks(exit_code, doc, body)

    console_variant = "verbose_console" if verbose else "console"
    _assert_frozen(scenario.name, doc, csv_text, body, console_variant=console_variant)


def test_hunt_all_all_not_evaluated(monkeypatch, tmp_path):
    """A fully empty FakeMF -> all 7 hunters NOT_EVALUATED -> summary.
    overall_status == "NOT_EVALUATED" -> coverage.status ==
    "not_evaluated" -> exit_code_for() now returns EXIT_NOT_EVALUATED (4),
    not 0 -- the coverage-based exit code PR4 brings `--hunt` onto, same
    as the ten other v2-routed commands already had. `--yara-dir` is
    pointed at a synthetic EMPTY tmp_path directory instead of the
    default packaged rules dir -- the packaged dir's own absolute host
    path would otherwise appear in the printed "Loaded N rule file(s)
    from <path>" line, making full console/JSON/CSV freezing impossible
    across machines/CI runners (same reasoning as `SCENARIOS["yara"]`'s
    own rules_dir placeholder). An empty directory still reaches
    yara_hunt's "no .yar/.yara files found" branch without ever importing
    yara-python, so this needs no optional dependency either. Not folded
    into `SCENARIOS`/`test_hunt_scenario_cli` -- it runs `--hunt all` (all
    7 hunters in one call, one 7-element `records` list), structurally
    different from every single-TTP scenario there."""
    from tests.fixtures.fakes import FakeMF
    mf = FakeMF()
    rules_dir = tmp_path / "empty_rules"
    rules_dir.mkdir()

    exit_code, doc, csv_text, console = run_cli(
        monkeypatch, tmp_path, ["--hunt", "all", "--yara-dir", str(rules_dir)], mf)

    assert exit_code == cli.EXIT_NOT_EVALUATED == 4
    assert doc["meta"]["execution"]["command"] == "hunt_all"
    assert doc["result"]["kind"] == "hunt"
    records = doc["result"]["data"]["records"]
    assert [r["hunter"] for r in records] == [
        "injection", "hollowing", "stomping", "pipe", "cs-beacon", "yara", "obfuscation"]
    assert all(r["status"] == "NOT_EVALUATED" for r in records)
    assert doc["result"]["summary"]["overall_status"] == "NOT_EVALUATED"
    assert doc["result"]["coverage"]["status"] == "not_evaluated"

    expected_records = json.loads((_GOLDEN / "all_hunt_dict.json").read_text(encoding="utf-8"))
    expected_csv = (_GOLDEN / "all_csv.txt").read_text(encoding="utf-8")
    expected_console = (_GOLDEN / "all_console.txt").read_text(encoding="utf-8")
    assert normalize_object_addresses(records) == expected_records
    assert csv_text == expected_csv
    body = split_console_body(console).replace(str(rules_dir), "<RULES_DIR>")
    assert body == expected_console
