"""--threads command."""
import ntpath
from dumpex.ui.colors import BOLD, DIM, RED, GREEN, YELLOW, CYAN
from dumpex.core.memory import get_modules, get_thread_infos, addr_to_module
from dumpex.core.pe_utils import _filetime_to_str, _dumpflags_str, _duration_100ns_to_str
from dumpex.output.records import (
    ThreadRecord, hex_address,
    MODULE_CONTEXT_RESOLVED, MODULE_CONTEXT_UNREGISTERED, MODULE_CONTEXT_UNAVAILABLE,
)
from dumpex.output.coverage import (
    observe_source, build_coverage_report, CoverageLimitation, LimitationCode, SourceState,
    SourceRequirement,
)
from dumpex.output.command_result import CommandResult

# The two field-name groups a ThreadInfoListStream absence/mismatch
# affects: what only ThreadInfoListStream provides vs. what only the base
# ThreadListStream provides. Shared between the "whole stream absent"
# (SourceRequirement) and "TID present in one stream but not the other"
# (SOURCE_KEY_MISMATCH) cases below, since both describe the same
# underlying field-availability split.
_THREAD_INFO_ONLY_FIELDS = ("StartAddress", "CreateTime", "ExitTime", "KernelTime", "UserTime")
_THREAD_BASE_ONLY_FIELDS = ("SuspendCount", "Priority", "TEB")

# Exact text render_limitation() produces for the degraded (ThreadInfoListStream
# absent) case -- kept here only so render_threads_console can recognize and
# skip it (the degraded banner above already covers this fact); the text
# itself is generated by coverage.py's SOURCE_ABSENT field-impact template,
# not composed here.
_DEGRADED_REASON = (
    f"ThreadInfoListStream not present; {'/'.join(_THREAD_INFO_ONLY_FIELDS)} "
    f"unavailable (TID/{'/'.join(_THREAD_BASE_ONLY_FIELDS)} only)"
)


class _RawThreadInfo:
    """
    Stand-in for a MINIDUMP_THREAD_INFO record, built from the base
    ThreadListStream when the optional ThreadInfoListStream isn't present
    in the dump. StartAddress/CreateTime/ExitTime/KernelTime/UserTime/
    ExitStatus/DumpFlags don't exist on the raw MINIDUMP_THREAD structure,
    so they stay None here rather than being guessed at.
    """
    __slots__ = ("ThreadId", "StartAddress", "CreateTime", "ExitTime",
                 "KernelTime", "UserTime", "ExitStatus", "DumpFlags")

    def __init__(self, tid):
        self.ThreadId     = tid
        self.StartAddress = None
        self.CreateTime    = None
        self.ExitTime      = None
        self.KernelTime    = None
        self.UserTime      = None
        self.ExitStatus    = None
        self.DumpFlags     = None


def thread_info_is_degraded(coverage) -> bool:
    """True when ThreadInfoListStream itself is absent while the base
    ThreadListStream is present -- the common, expected "not captured
    with MiniDumpWithThreadInfo" case, tracked separately from a per-TID
    mismatch between two streams that ARE both present (see
    collect_threads' docstring). Derived from the CoverageReport's own
    per-source state rather than threaded through as a separate return
    value, so collect_threads' return type stays a plain CommandResult."""
    return (coverage.sources["thread_info"].state == SourceState.ABSENT
            and coverage.sources["threads"].state != SourceState.ABSENT)


def thread_records_have_times(records) -> bool:
    """True if any built record carries a create_time. Equivalent to
    collect_threads' internal has_times (which gates whether
    create_time/exit_time get populated AT ALL for real, non-placeholder
    entries) once records already exist: has_times is True iff at least
    one real entry had a truthy CreateTime, in which case every real
    entry's create_time is a formatted string, not None -- so this can be
    recovered from the records themselves instead of a separate return
    value."""
    return any(rec.create_time is not None for rec in records)


def collect_threads(mf) -> CommandResult:
    """
    Pure data, no printing. Returns a CommandResult[ThreadRecord].
    `degraded`/`has_times` -- extra rendering context specific to this
    command (whether ThreadInfoListStream was present, and whether any
    thread reports timing fields at all), consumed only by
    render_threads_console -- are derived from the result via
    thread_info_is_degraded()/thread_records_have_times() rather than
    returned separately (see cmd_threads below).

    ThreadListStream and ThreadInfoListStream are two independent,
    independently-optional streams describing the same threads. Neither
    stream's mere PRESENCE tells you the two actually agree on which
    TIDs exist -- a dump can have both streams and still have a TID in
    one that's absent from the other (a stream that's present but
    reports fewer threads than the other, or a genuinely inconsistent
    capture). Building the record set from ONE stream's TID list alone
    would silently drop threads the other stream knows about, and would
    report 'complete' coverage for a dump where the two streams actually
    disagree. Records are built from the UNION of both streams' TIDs;
    whichever stream is missing a given TID has its own fields filled in
    via _RawThreadInfo's None placeholders for that thread specifically,
    and the mismatch count is a coverage reason -- not silently absorbed
    into either "complete" or a single all-or-nothing 'degraded' flag.

    Every non-mismatch reason here (thread_info absent, modules absent,
    both thread streams absent) is auto-derived by build_coverage_report()
    from the SourceObservations above via `evaluation_sources`/
    `completeness_checks` -- this command never hand-builds a
    SOURCE_ABSENT/SOURCE_GROUP_ABSENT/MODULE_CLASSIFICATION_UNAVAILABLE
    CoverageLimitation itself, so a future edit here can't accidentally
    drop one of those checks and silently report "complete". Only the
    TID-level SOURCE_KEY_MISMATCH limitations (missing_from_info/
    missing_from_base below) are hand-built, since a cross-source key
    mismatch is business logic the reducer cannot infer from source
    state alone.
    """
    base_threads_present = bool(mf.threads)
    info_stream_present  = bool(mf.thread_info)
    modules_available    = bool(mf.modules)

    threads_by_tid = {t.ThreadId: t for t in (mf.threads.threads if mf.threads else [])}
    real_infos_by_tid = {ti.ThreadId: ti for ti in get_thread_infos(mf)}
    modules = get_modules(mf)

    threads_source      = observe_source("threads", present=base_threads_present,
                                          items=list(threads_by_tid.values()))
    thread_info_source  = observe_source("thread_info", present=info_stream_present,
                                          items=list(real_infos_by_tid.values()))
    modules_source       = observe_source("modules", present=modules_available, items=modules)
    sources = {"threads": threads_source, "thread_info": thread_info_source, "modules": modules_source}

    if not base_threads_present and not info_stream_present:
        # Neither stream exists at all -- there is no thread data of any
        # kind to report, not "0 threads, fully evaluated." The
        # SOURCE_GROUP_ABSENT reason ("Neither ThreadListStream nor
        # ThreadInfoListStream present in this dump") is generated
        # automatically from evaluation_sources below, not built here.
        coverage = build_coverage_report(sources, evaluation_sources=("threads", "thread_info"))
        return CommandResult(kind="threads", records=[], coverage=coverage, summary={"count": 0})

    # Whole-stream absence (the common, expected "not captured with
    # MiniDumpWithThreadInfo" case) is still tracked separately from a
    # per-TID mismatch between two streams that ARE both present, since
    # it gets its own specific, more actionable console message below.
    degraded = not info_stream_present and base_threads_present

    all_tids = list(threads_by_tid.keys())
    for tid in real_infos_by_tid:
        if tid not in threads_by_tid:
            all_tids.append(tid)

    missing_from_info = 0   # TID in ThreadListStream, absent from ThreadInfoListStream
    missing_from_base = 0   # TID in ThreadInfoListStream, absent from ThreadListStream
    # (ti, is_placeholder) pairs -- is_placeholder marks a _RawThreadInfo
    # synthesized because this specific TID has no ThreadInfoListStream
    # entry (whether because the whole stream is absent, or just this
    # one TID is missing from an otherwise-present stream). Tracked
    # per-record, not as a single dump-wide flag: a merged result can
    # freely mix real entries and placeholders, and a placeholder must
    # never be rendered as if it were a real "no timestamp recorded"
    # answer -- see has_times' per-record use below.
    entries = []
    for tid in all_tids:
        ti = real_infos_by_tid.get(tid)
        if ti is None:
            if info_stream_present and not degraded:
                # ThreadInfoListStream exists (and isn't entirely absent)
                # but doesn't cover this specific TID -- a genuine
                # per-thread gap, counted once via the whole-stream
                # 'degraded' reason instead when the stream is absent
                # altogether.
                missing_from_info += 1
            ti = _RawThreadInfo(tid)
            entries.append((ti, True))
            continue
        if tid not in threads_by_tid and info_stream_present:
            missing_from_base += 1
        entries.append((ti, False))

    # Dump-wide: does ThreadInfoListStream carry meaningful timing data
    # at all (some minidump producers leave CreateTime/ExitTime zeroed
    # even when the stream itself is present)? Only checked over REAL
    # entries -- a placeholder's CreateTime is always None and must not
    # be able to suppress this for the whole result on its own, nor
    # (see the per-record gating below) borrow a "yes" from unrelated
    # real threads elsewhere in the same result.
    has_times = any(getattr(ti, "CreateTime", None) for ti, is_placeholder in entries
                     if not is_placeholder)

    records = []
    for ti, is_placeholder in entries:
        sa  = ti.StartAddress   # may be None in degraded mode — do not coerce to 0

        module_context = None   # start address itself unknown -- module context is moot
        mod = None
        if sa is not None:
            mod = addr_to_module(sa, modules)
            if mod is not None:
                module_context = MODULE_CONTEXT_RESOLVED
            elif modules_available:
                # ModuleListStream WAS available and this address genuinely
                # isn't in it -- a real, confirmed finding (this tool's own
                # injection/hollowing hunters treat an unbacked thread start
                # address as a suspicious indicator).
                module_context = MODULE_CONTEXT_UNREGISTERED
            else:
                # ModuleListStream itself is missing -- we simply cannot
                # tell either way. Must never be indistinguishable from
                # MODULE_CONTEXT_UNREGISTERED above, which IS a signal.
                module_context = MODULE_CONTEXT_UNAVAILABLE

        raw           = threads_by_tid.get(ti.ThreadId)
        suspend_count = getattr(raw, "SuspendCount", None) if raw else None
        priority      = getattr(raw, "Priority", None) if raw else None
        teb           = getattr(raw, "Teb", None) if raw else None

        flag_tag    = _dumpflags_str(getattr(ti, "DumpFlags", None))
        exit_status = getattr(ti, "ExitStatus", None)
        exited      = flag_tag == "[EXITED]"

        # A placeholder never gets a create_time/exit_time value, no
        # matter what has_times says about the rest of the result -- it
        # has no real ThreadInfoListStream entry at all, which is not
        # the same claim as "this stream reports no timestamp."
        create_time = (_filetime_to_str(getattr(ti, "CreateTime", 0) or 0)
                       if (has_times and not is_placeholder) else None)
        exit_time   = (_filetime_to_str(getattr(ti, "ExitTime", 0) or 0)
                       if (has_times and not is_placeholder and exited) else None)

        records.append(ThreadRecord(
            tid=ti.ThreadId,
            start_address=hex_address(sa) if sa is not None else None,
            # ntpath.basename, not os.path.basename -- module paths are
            # Windows paths regardless of the host OS this tool runs on
            # (see dumpex.hunt.stomping.memory_scan._module_basename).
            backing_module=ntpath.basename(mod.name) if mod else None,
            module_context=module_context,
            flags=[flag_tag.strip("[]")] if flag_tag else [],
            create_time=create_time,
            exit_time=exit_time,
            exit_status=exit_status,
            kernel_time_100ns=getattr(ti, "KernelTime", None),
            user_time_100ns=getattr(ti, "UserTime", None),
            suspend_count=suspend_count,
            priority=priority,
            teb=hex_address(teb) if teb else None,
        ))

    # Ordered exactly like the reasons this command has always shipped:
    # thread_info's own absence (if any) first, then either TID-mismatch
    # direction (if any), then modules' absence last. thread_info/modules
    # entries are SourceRequirements -- the reducer derives their
    # limitation (or none at all) from the SourceObservations built
    # above; only the TID-mismatch entries are hand-built CoverageLimitations,
    # since a cross-source key mismatch isn't something the reducer can
    # infer from source state alone.
    completeness_checks = [
        SourceRequirement("thread_info", absent_code=LimitationCode.SOURCE_ABSENT,
                           unavailable_fields=_THREAD_INFO_ONLY_FIELDS,
                           available_fields=("TID",) + _THREAD_BASE_ONLY_FIELDS),
    ]
    if missing_from_info:
        completeness_checks.append(CoverageLimitation(
            code=LimitationCode.SOURCE_KEY_MISMATCH, source="thread_info",
            counterpart_source="threads", scope="thread", affected_count=missing_from_info,
            unavailable_fields=_THREAD_INFO_ONLY_FIELDS))
    if missing_from_base:
        completeness_checks.append(CoverageLimitation(
            code=LimitationCode.SOURCE_KEY_MISMATCH, source="threads",
            counterpart_source="thread_info", scope="thread", affected_count=missing_from_base,
            unavailable_fields=_THREAD_BASE_ONLY_FIELDS))
    completeness_checks.append(
        SourceRequirement("modules", absent_code=LimitationCode.MODULE_CLASSIFICATION_UNAVAILABLE))

    coverage = build_coverage_report(
        sources,
        evaluation_sources=("threads", "thread_info"),
        completeness_checks=completeness_checks,
    )
    return CommandResult(kind="threads", records=records, coverage=coverage,
                          summary={"count": len(records)})


def render_threads_console(records, degraded: bool, has_times: bool,
                            coverage_reasons: list = None) -> None:
    if degraded:
        print(YELLOW(
            "  [~] ThreadInfoListStream not present in this dump — falling back to the\n"
            "      base ThreadListStream. StartAddress / CreateTime / ExitTime / Kernel-\n"
            "      UserTime are NOT available in this mode (only TID / SuspendCount /\n"
            "      Priority / TEB, from the raw thread record).\n"))

    # Every OTHER coverage gap (a per-TID mismatch between the two thread
    # streams, or a missing ModuleListStream) gets a plain warning line --
    # the degraded banner above already covers its own specific reason,
    # so it's skipped here to avoid printing the same fact twice.
    for reason in (coverage_reasons or []):
        if reason == _DEGRADED_REASON:
            continue
        print(YELLOW(f"  [~] {reason}\n"))

    for rec in records:
        flag_tag = f"[{rec.flags[0]}]" if rec.flags else ""
        exited   = "EXITED" in rec.flags

        tid_str = f"0x{rec.tid:x}"
        if flag_tag == "[DUMPER]":
            tid_str = CYAN(tid_str) + f" {CYAN(flag_tag)}"
        elif exited:
            tid_str = DIM(tid_str) + f" {DIM(flag_tag)}"
        elif flag_tag:
            tid_str = YELLOW(tid_str) + f" {YELLOW(flag_tag)}"

        print(f"\n  {BOLD('TID')}              {tid_str}")
        if rec.start_address is None:
            backed = DIM("(unknown — requires ThreadInfoListStream)")
            print(f"  {'StartAddress':<16} {DIM('unavailable')}  ← {backed}")
        else:
            if rec.module_context == MODULE_CONTEXT_RESOLVED:
                backed = DIM(rec.backing_module)
            elif rec.module_context == MODULE_CONTEXT_UNREGISTERED:
                # Confirmed: ModuleListStream was available and this
                # address genuinely isn't backed by any known module.
                backed = RED("⚠  NOT IN ANY MODULE")
            else:
                # MODULE_CONTEXT_UNAVAILABLE -- ModuleListStream itself
                # missing; must not read as the confirmed anomaly above.
                backed = YELLOW("(module data unavailable — ModuleListStream missing)")
            print(f"  {'StartAddress':<16} {rec.start_address}  ← {backed}")
        if rec.suspend_count is not None:
            # SuspendCount > 0 has legitimate benign explanations (thread
            # pool management, a debugger attach, a thread not yet resumed
            # after CreateThread) as well as injection-prep ones — report
            # it as notable, not as a definitive verdict either way.
            susp_str = (YELLOW(f"{rec.suspend_count}  (non-zero — can indicate injection prep, "
                               f"debugging, or benign suspension; not conclusive alone)")
                        if rec.suspend_count > 0 else str(rec.suspend_count))
            print(f"  {'SuspendCount':<16} {susp_str}")
        if rec.priority is not None:
            print(f"  {'Priority':<16} {rec.priority}")
        if rec.teb:
            print(f"  {'TEB':<16} {rec.teb}")
        if rec.create_time is not None:
            # Gated on THIS record's own create_time, not the dump-wide
            # has_times flag -- a merged result can mix real
            # ThreadInfoListStream entries with placeholder threads that
            # have none at all, and a placeholder must never print
            # "Exited: (still running)" as if that had been confirmed.
            print(f"  {'Created':<16} {rec.create_time}")
            if exited:
                print(f"  {'Exited':<16} {YELLOW(rec.exit_time)}")
                if rec.exit_status is not None:
                    code_str = f"0x{rec.exit_status:x}"
                    label    = YELLOW(code_str) if rec.exit_status else DIM(code_str + " (clean)")
                    print(f"  {'ExitStatus':<16} {label}")
            else:
                print(f"  {'Exited':<16} {DIM('(still running)')}")
        if rec.kernel_time_100ns is not None:
            print(f"  {'KernelTime':<16} {_duration_100ns_to_str(rec.kernel_time_100ns)}")
        if rec.user_time_100ns is not None:
            print(f"  {'UserTime':<16} {_duration_100ns_to_str(rec.user_time_100ns)}")

    if not has_times and not degraded:
        # NOT the same claim as the degraded-mode banner above: degraded
        # means ThreadInfoListStream itself is absent, but this branch
        # also fires when the stream IS present and every real entry's
        # CreateTime just happens to be zero/unset (some minidump
        # producers never populate it even though the stream exists) --
        # a neutral "not available in the captured data" is accurate in
        # both cases, whereas naming ThreadInfoListStream specifically
        # would be wrong for the "stream present, empty timestamps" one.
        print(f"\n  {DIM('[~] CreateTime/ExitTime not available in the captured ThreadInfo data.')}")

    print(f"\n{GREEN(f'[+] {len(records)} thread(s).')}")


def cmd_threads(mf) -> CommandResult:
    result = collect_threads(mf)
    degraded  = thread_info_is_degraded(result.coverage)
    has_times = thread_records_have_times(result.records)
    render_threads_console(result.records, degraded, has_times, result.coverage.reasons)
    return result
