"""--threads command."""
import ntpath
from dumpex.ui.colors import BOLD, DIM, RED, GREEN, YELLOW, CYAN, console_safe
from dumpex.core.memory import (
    get_modules, get_thread_infos, enriched_thread_contexts, addr_to_module, RawThreadInfo,
)
from dumpex.core.pe_utils import _filetime_to_str, _dumpflags_str, _duration_100ns_to_str
from dumpex.output.records import (
    ThreadRecord, hex_address,
    MODULE_CONTEXT_RESOLVED, MODULE_CONTEXT_UNREGISTERED, MODULE_CONTEXT_UNAVAILABLE,
)
from dumpex.output.coverage import (
    observe_source, build_coverage_report, CoverageLimitation, LimitationCode, SourceState,
    SourceRequirement,
)
from dumpex.output.command_result import CommandResult

# The two field-name groups a ThreadInfoListStream absence/mismatch
# affects: what only ThreadInfoListStream provides vs. what only the base
# ThreadListStream provides. Shared between the "whole stream absent"
# (SourceRequirement) and "TID present in one stream but not the other"
# (SOURCE_KEY_MISMATCH) cases below, since both describe the same
# underlying field-availability split. CurrentIP (ip/ip_reg) belongs in
# the BASE-only group, not the ThreadInfoListStream-only one: it comes
# from this thread's own CONTEXT on the base ThreadListStream (see
# get_thread_contexts), so a TID missing from the base stream loses it
# exactly like SuspendCount/Priority/TEB, and a TID missing only from
# ThreadInfoListStream keeps it. DumpFlags belongs in the
# ThreadInfoListStream-only group -- it doesn't exist on the raw
# MINIDUMP_THREAD structure (see RawThreadInfo) -- so a TID missing that
# record loses not just `flags` but the ability to check `ip` against it
# at all: ip_context_conflict_for() reports that as None (undeterminable),
# never a confirmed False, and this is the fact that tells a consumer why.
_THREAD_INFO_ONLY_FIELDS = ("StartAddress", "CreateTime", "ExitTime", "KernelTime", "UserTime",
                             "DumpFlags")
_THREAD_BASE_ONLY_FIELDS = ("SuspendCount", "Priority", "TEB", "CurrentIP")

# Exact text render_limitation() produces for the degraded (ThreadInfoListStream
# absent) case -- kept here only so render_threads_console can recognize and
# skip it (the degraded banner above already covers this fact); the text
# itself is generated by coverage.py's SOURCE_ABSENT field-impact template,
# not composed here.
_DEGRADED_REASON = (
    f"ThreadInfoListStream not present; {'/'.join(_THREAD_INFO_ONLY_FIELDS)} "
    f"unavailable (TID/{'/'.join(_THREAD_BASE_ONLY_FIELDS)} only)"
)


def thread_info_is_degraded(coverage) -> bool:
    """True when ThreadInfoListStream itself is absent while the base
    ThreadListStream is present -- the common, expected "not captured
    with MiniDumpWithThreadInfo" case, tracked separately from a per-TID
    mismatch between two streams that ARE both present (see
    collect_threads' docstring). Derived from the CoverageReport's own
    per-source state rather than threaded through as a separate return
    value, so collect_threads' return type stays a plain CommandResult."""
    return (coverage.sources["thread_info"].state == SourceState.ABSENT
            and coverage.sources["threads"].state != SourceState.ABSENT)


def thread_records_have_times(records) -> bool:
    """True if any built record carries a create_time. Equivalent to
    collect_threads' internal has_times (which gates whether
    create_time/exit_time get populated AT ALL for real, non-placeholder
    entries) once records already exist: has_times is True iff at least
    one real entry had a truthy CreateTime, in which case every real
    entry's create_time is a formatted string, not None -- so this can be
    recovered from the records themselves instead of a separate return
    value."""
    return any(rec.create_time is not None for rec in records)


def thread_records_have_context(records) -> bool:
    """True if any built record carries a live current IP. Same
    recompute-from-records shape as thread_records_have_times() above --
    unlike has_times, CurrentIP is never gated per-record on
    is_placeholder in collect_threads(): a TID's own CONTEXT comes from
    the base ThreadListStream and is available independent of whether
    ThreadInfoListStream covers that TID (see collect_threads' own note
    on why has_context there is NOT gated the way has_times is)."""
    return any(rec.ip is not None for rec in records)


def collect_threads(mf) -> CommandResult:
    """Collect thread records and evidence coverage without rendering.

    ThreadListStream and ThreadInfoListStream are independent. Records use the
    union of their TIDs so a stream mismatch cannot silently drop a thread.
    Missing per-stream fields remain None, and key mismatches become explicit
    cross-source limitations. Other absent-source limitations are derived from
    SourceObservations by the shared coverage reducer.
    """
    base_threads_present = bool(mf.threads)
    info_stream_present  = bool(mf.thread_info)
    modules_available    = bool(mf.modules)

    threads_by_tid = {t.ThreadId: t for t in (mf.threads.threads if mf.threads else [])}
    real_infos_by_tid = {ti.ThreadId: ti for ti in get_thread_infos(mf)}
    modules = get_modules(mf)
    # Per-thread live RIP/EIP, independent of ThreadInfoListStream --
    # "TID not in this map" is get_thread_contexts' own "no CONTEXT
    # captured/parsed for this thread" contract, never treated as "current
    # IP is 0" nor backfilled from that same thread's own StartAddress.
    contexts_by_tid = {c["ThreadId"]: c for c in enriched_thread_contexts(mf)}

    threads_source      = observe_source("threads", present=base_threads_present,
                                          items=list(threads_by_tid.values()))
    thread_info_source  = observe_source("thread_info", present=info_stream_present,
                                          items=list(real_infos_by_tid.values()))
    modules_source       = observe_source("modules", present=modules_available, items=modules)
    sources = {"threads": threads_source, "thread_info": thread_info_source, "modules": modules_source}

    if not base_threads_present and not info_stream_present:
        # Neither stream exists at all -- there is no thread data of any
        # kind to report, not "0 threads, fully evaluated." The
        # SOURCE_GROUP_ABSENT reason ("Neither ThreadListStream nor
        # ThreadInfoListStream present in this dump") is generated
        # automatically from evaluation_sources below, not built here.
        coverage = build_coverage_report(sources, evaluation_sources=("threads", "thread_info"))
        return CommandResult(kind="threads", records=[], coverage=coverage, summary={"count": 0})

    # Whole-stream absence (the common, expected "not captured with
    # MiniDumpWithThreadInfo" case) is still tracked separately from a
    # per-TID mismatch between two streams that ARE both present, since
    # it gets its own specific, more actionable console message below.
    degraded = not info_stream_present and base_threads_present

    all_tids = list(threads_by_tid.keys())
    for tid in real_infos_by_tid:
        if tid not in threads_by_tid:
            all_tids.append(tid)

    missing_from_info = 0   # TID in ThreadListStream, absent from ThreadInfoListStream
    missing_from_base = 0   # TID in ThreadInfoListStream, absent from ThreadListStream
    # (ti, is_placeholder) pairs -- is_placeholder marks a RawThreadInfo
    # synthesized because this specific TID has no ThreadInfoListStream
    # entry (whether because the whole stream is absent, or just this
    # one TID is missing from an otherwise-present stream). Tracked
    # per-record, not as a single dump-wide flag: a merged result can
    # freely mix real entries and placeholders, and a placeholder must
    # never be rendered as if it were a real "no timestamp recorded"
    # answer -- see has_times' per-record use below.
    entries = []
    for tid in all_tids:
        ti = real_infos_by_tid.get(tid)
        if ti is None:
            if info_stream_present and not degraded:
                # ThreadInfoListStream exists (and isn't entirely absent)
                # but doesn't cover this specific TID -- a genuine
                # per-thread gap, counted once via the whole-stream
                # 'degraded' reason instead when the stream is absent
                # altogether.
                missing_from_info += 1
            ti = RawThreadInfo(tid)
            entries.append((ti, True))
            continue
        if tid not in threads_by_tid and info_stream_present:
            missing_from_base += 1
        entries.append((ti, False))

    # Dump-wide: does ThreadInfoListStream carry meaningful timing data
    # at all (some minidump producers leave CreateTime/ExitTime zeroed
    # even when the stream itself is present)? Only checked over REAL
    # entries -- a placeholder's CreateTime is always None and must not
    # be able to suppress this for the whole result on its own, nor
    # (see the per-record gating below) borrow a "yes" from unrelated
    # real threads elsewhere in the same result.
    has_times = any(getattr(ti, "CreateTime", None) for ti, is_placeholder in entries
                     if not is_placeholder)

    # CONTEXT comes from the base ThreadListStream itself (see
    # get_thread_contexts), entirely independent of ThreadInfoListStream --
    # so the per-record lookup below is NOT gated on is_placeholder the
    # way has_times is: a TID with no ThreadInfoListStream entry
    # (StartAddress/CreateTime/etc all unknown) can still have a
    # perfectly real, independently-sourced CONTEXT, and gating it on the
    # same placeholder flag would make CurrentIP wrongly inherit
    # StartAddress's own "unknown" state. The dump-wide has_context fact
    # render_threads_console needs is recomputed from the built records
    # via thread_records_have_context() below, not tracked here.

    records = []
    for ti, is_placeholder in entries:
        sa  = ti.StartAddress   # may be None in degraded mode — do not coerce to 0
        ctx = contexts_by_tid.get(ti.ThreadId)
        ip     = ctx["ip"]     if ctx is not None else None
        ip_reg = ctx["ip_reg"] if ctx is not None else None

        module_context = None   # start address itself unknown -- module context is moot
        mod = None
        if sa is not None:
            mod = addr_to_module(sa, modules)
            if mod is not None:
                module_context = MODULE_CONTEXT_RESOLVED
            elif modules_available:
                # ModuleListStream WAS available and this address genuinely
                # isn't in it -- a real, confirmed finding (this tool's own
                # injection/hollowing hunters treat an unbacked thread start
                # address as a suspicious indicator).
                module_context = MODULE_CONTEXT_UNREGISTERED
            else:
                # ModuleListStream itself is missing -- we simply cannot
                # tell either way. Must never be indistinguishable from
                # MODULE_CONTEXT_UNREGISTERED above, which IS a signal.
                module_context = MODULE_CONTEXT_UNAVAILABLE

        raw           = threads_by_tid.get(ti.ThreadId)
        suspend_count = getattr(raw, "SuspendCount", None) if raw else None
        priority      = getattr(raw, "Priority", None) if raw else None
        teb           = getattr(raw, "Teb", None) if raw else None

        flag_tag    = _dumpflags_str(getattr(ti, "DumpFlags", None))
        exit_status = getattr(ti, "ExitStatus", None)
        exited      = flag_tag == "[EXITED]"
        # Tri-state: undeterminable (None), not just False, when this TID
        # has no real ThreadInfoListStream record to join `ip` against --
        # see ip_context_conflict_for's own docstring and ThreadRecord.
        # ip_context_conflict's identical rule (the same derivation
        # dumpex.commands.report uses for ReportThreadInfo.ip_context_conflict).
        # False, never None, when this TID has no captured CONTEXT at all
        # (ctx is None): there is no `ip` to dispute either way.
        ip_context_conflict = ctx["ip_context_conflict"] if ctx is not None else False

        # A placeholder never gets a create_time/exit_time value, no
        # matter what has_times says about the rest of the result -- it
        # has no real ThreadInfoListStream entry at all, which is not
        # the same claim as "this stream reports no timestamp."
        create_time = (_filetime_to_str(getattr(ti, "CreateTime", 0) or 0)
                       if (has_times and not is_placeholder) else None)
        exit_time   = (_filetime_to_str(getattr(ti, "ExitTime", 0) or 0)
                       if (has_times and not is_placeholder and exited) else None)

        records.append(ThreadRecord(
            tid=ti.ThreadId,
            start_address=hex_address(sa) if sa is not None else None,
            ip=hex_address(ip) if ip is not None else None,
            ip_reg=ip_reg,
            # ntpath.basename, not os.path.basename -- module paths are
            # Windows paths regardless of the host OS this tool runs on
            # (see dumpex.hunt.stomping.memory_scan._module_basename).
            backing_module=ntpath.basename(mod.name) if mod else None,
            module_context=module_context,
            flags=[flag_tag.strip("[]")] if flag_tag else [],
            create_time=create_time,
            exit_time=exit_time,
            exit_status=exit_status,
            kernel_time_100ns=getattr(ti, "KernelTime", None),
            user_time_100ns=getattr(ti, "UserTime", None),
            suspend_count=suspend_count,
            priority=priority,
            teb=hex_address(teb) if teb else None,
            ip_context_conflict=ip_context_conflict,
        ))

    # Ordered exactly like the reasons this command has always shipped:
    # thread_info's own absence (if any) first, then either TID-mismatch
    # direction (if any), then threads' own absence (if any -- same
    # position missing_from_base's reason used to occupy, since the two
    # are mutually exclusive: missing_from_base only fires when threads
    # is genuinely PRESENT but partially mismatched), then modules'
    # absence last.
    #
    # thread_info/threads/modules entries are SourceRequirements -- the
    # reducer derives their limitation (or none at all) from the
    # SourceObservations built above; only the TID-mismatch entries are
    # hand-built CoverageLimitations, since a cross-source key mismatch
    # isn't something the reducer can infer from source state alone.
    #
    # missing_from_base is gated on base_threads_present specifically so
    # a fully-absent ThreadListStream never renders as SOURCE_KEY_MISMATCH
    # (a PARTIAL mismatch between two present sources) -- it goes through
    # the "threads" SourceRequirement below instead, which the reducer
    # only fires when threads.state is genuinely ABSENT, producing the
    # correct SOURCE_ABSENT code with the SAME "N present in
    # ThreadInfoListStream but missing from ThreadListStream (...)"
    # wording via counterpart_source/affected_count/unavailable_fields.
    completeness_checks = [
        SourceRequirement("thread_info", absent_code=LimitationCode.SOURCE_ABSENT,
                           unavailable_fields=_THREAD_INFO_ONLY_FIELDS,
                           available_fields=("TID",) + _THREAD_BASE_ONLY_FIELDS),
    ]
    if missing_from_info:
        completeness_checks.append(CoverageLimitation(
            code=LimitationCode.SOURCE_KEY_MISMATCH, source="thread_info",
            counterpart_source="threads", scope="thread", affected_count=missing_from_info,
            unavailable_fields=_THREAD_INFO_ONLY_FIELDS))
    if base_threads_present and missing_from_base:
        completeness_checks.append(CoverageLimitation(
            code=LimitationCode.SOURCE_KEY_MISMATCH, source="threads",
            counterpart_source="thread_info", scope="thread", affected_count=missing_from_base,
            unavailable_fields=_THREAD_BASE_ONLY_FIELDS))
    completeness_checks.append(SourceRequirement(
        "threads", absent_code=LimitationCode.SOURCE_ABSENT, counterpart_source="thread_info",
        scope="thread", affected_count=missing_from_base, unavailable_fields=_THREAD_BASE_ONLY_FIELDS))
    completeness_checks.append(
        SourceRequirement("modules", absent_code=LimitationCode.MODULE_CLASSIFICATION_UNAVAILABLE))

    coverage = build_coverage_report(
        sources,
        evaluation_sources=("threads", "thread_info"),
        completeness_checks=completeness_checks,
    )
    return CommandResult(kind="threads", records=records, coverage=coverage,
                          summary={"count": len(records)})


def render_threads_console(records, coverage) -> None:
    """Takes the whole records list and CoverageReport, not a
    (degraded, has_times, reasons) triple derived from them separately --
    both are recomputed here via thread_info_is_degraded()/
    thread_records_have_times() rather than trusted from a stale call
    site, matching every other recon renderer's (record, coverage)
    contract."""
    degraded = thread_info_is_degraded(coverage)
    has_times = thread_records_have_times(records)
    has_context = thread_records_have_context(records)
    coverage_reasons = coverage.reasons

    if degraded:
        print(YELLOW(
            "  [~] ThreadInfoListStream not present in this dump — falling back to the\n"
            "      base ThreadListStream. StartAddress / CreateTime / ExitTime / Kernel-\n"
            "      UserTime / DumpFlags are NOT available in this mode (only TID /\n"
            "      SuspendCount / Priority / TEB / CurrentIP, from the raw thread record\n"
            "      and its own captured CONTEXT) -- ip_context_conflict is unconfirmable\n"
            "      (not a confirmed False) for every thread shown.\n"))

    # Every OTHER coverage gap (a per-TID mismatch between the two thread
    # streams, or a missing ModuleListStream) gets a plain warning line --
    # the degraded banner above already covers its own specific reason,
    # so it's skipped here to avoid printing the same fact twice.
    for reason in (coverage_reasons or []):
        if reason == _DEGRADED_REASON:
            continue
        print(YELLOW(f"  [~] {reason}\n"))

    for rec in records:
        flag_tag = f"[{rec.flags[0]}]" if rec.flags else ""
        exited   = "EXITED" in rec.flags

        tid_str = f"0x{rec.tid:x}"
        if flag_tag == "[DUMPER]":
            tid_str = CYAN(tid_str) + f" {CYAN(flag_tag)}"
        elif exited:
            tid_str = DIM(tid_str) + f" {DIM(flag_tag)}"
        elif flag_tag:
            tid_str = YELLOW(tid_str) + f" {YELLOW(flag_tag)}"

        print(f"\n  {BOLD('TID')}              {tid_str}")
        if rec.start_address is None:
            backed = DIM("(unknown — requires ThreadInfoListStream)")
            print(f"  {'StartAddress':<16} {DIM('unavailable')}  ← {backed}")
        else:
            if rec.module_context == MODULE_CONTEXT_RESOLVED:
                # ntpath.basename() of a ModuleListStream name -- a dump
                # string, so escaped before the colour helper. The other
                # two branches print dumpex's own fixed text.
                backed = DIM(console_safe(rec.backing_module))
            elif rec.module_context == MODULE_CONTEXT_UNREGISTERED:
                # Confirmed: ModuleListStream was available and this
                # address genuinely isn't backed by any known module.
                backed = RED("⚠  NOT IN ANY MODULE")
            else:
                # MODULE_CONTEXT_UNAVAILABLE -- ModuleListStream itself
                # missing; must not read as the confirmed anomaly above.
                backed = YELLOW("(module data unavailable — ModuleListStream missing)")
            print(f"  {'StartAddress':<16} {rec.start_address}  ← {backed}")
        # CurrentIP is this thread's OWN captured CONTEXT, independent of
        # StartAddress above -- never inferred from it and never printed
        # as if the two were the same fact under two names.
        if rec.ip is None:
            unavailable = DIM("(no CONTEXT captured/parsed for this thread)")
            print(f"  {'CurrentIP':<16} {DIM('unavailable')}  ← {unavailable}")
        else:
            ip_val = int(rec.ip, 16)
            zero_note = ("zero — not treated as a confirmed execution address"
                         if ip_val == 0 else None)
            if rec.ip_context_conflict is None:
                # This TID has no ThreadInfoListStream record at all to
                # join `ip` against (see ip_context_conflict_for) -- the
                # dispute status is undeterminable, never a confirmed
                # "not disputed" the way a genuinely clean DumpFlags is.
                undeterminable = "cannot confirm whether this context is disputed — no ThreadInfoListStream record for this thread"
                note = DIM(f" ({zero_note}; {undeterminable})" if zero_note
                           else f" ({undeterminable})")
            elif zero_note and rec.ip_context_conflict:
                # Both facts are real and neither one explains the other
                # away: the value is genuinely captured as 0x0 (see
                # get_thread_contexts), AND this TID's own
                # ThreadInfoListStream record independently flags this
                # same context as invalid -- a conflicted value must not
                # be reported as merely zero.
                note = DIM(" (dump reports this thread's context as invalid — not confirmed; "
                           "captured value is 0x0)")
            elif zero_note:
                # A genuinely-zero CONTEXT is real captured data (see
                # get_thread_contexts) but is not treated as a usable
                # execution address anywhere else in this tool either
                # (the instruction-anchor candidate filter requires
                # addr > 0) -- never annotated as if it were a confirmed
                # divergent execution location.
                note = DIM(f" ({zero_note})")
            elif rec.ip_context_conflict:
                # The dump producer's own ThreadInfoListStream record
                # says this thread's context could not be retrieved --
                # a parsed base-ThreadListStream CONTEXT existing anyway
                # is a genuine disagreement between the two sources, not
                # a confirmed divergent execution location. Reach is
                # narrower than a bitwise DumpFlags check would give:
                # upstream `minidump` parses DumpFlags via a plain
                # single-member Enum lookup (MINIDUMP_THREAD_INFO.parse,
                # `DumpFlags(raw_int)`), so a genuinely-combined flag
                # value (e.g. EXITED_THREAD | INVALID_CONTEXT) fails that
                # lookup and leaves DumpFlags -- and this tag -- unset.
                # This branch only ever fires for the single, exact
                # INVALID_CONTEXT value.
                note = DIM(" (dump reports this thread's context as invalid — not confirmed)")
            else:
                diverges = (rec.start_address is not None and rec.ip != rec.start_address)
                note = DIM(" (differs from StartAddress)") if diverges else ""
            print(f"  {'CurrentIP':<16} {rec.ip}  ({rec.ip_reg}){note}")
        if rec.suspend_count is not None:
            # SuspendCount > 0 has legitimate benign explanations (thread
            # pool management, a debugger attach, a thread not yet resumed
            # after CreateThread) as well as injection-prep ones — report
            # it as notable, not as a definitive verdict either way.
            susp_str = (YELLOW(f"{rec.suspend_count}  (non-zero — can indicate injection prep, "
                               f"debugging, or benign suspension; not conclusive alone)")
                        if rec.suspend_count > 0 else str(rec.suspend_count))
            print(f"  {'SuspendCount':<16} {susp_str}")
        if rec.priority is not None:
            print(f"  {'Priority':<16} {rec.priority}")
        if rec.teb:
            print(f"  {'TEB':<16} {rec.teb}")
        if rec.create_time is not None:
            # Gated on THIS record's own create_time, not the dump-wide
            # has_times flag -- a merged result can mix real
            # ThreadInfoListStream entries with placeholder threads that
            # have none at all, and a placeholder must never print
            # "Exited: (still running)" as if that had been confirmed.
            print(f"  {'Created':<16} {rec.create_time}")
            if exited:
                print(f"  {'Exited':<16} {YELLOW(rec.exit_time)}")
                if rec.exit_status is not None:
                    code_str = f"0x{rec.exit_status:x}"
                    label    = YELLOW(code_str) if rec.exit_status else DIM(code_str + " (clean)")
                    print(f"  {'ExitStatus':<16} {label}")
            else:
                print(f"  {'Exited':<16} {DIM('(still running)')}")
        if rec.kernel_time_100ns is not None:
            print(f"  {'KernelTime':<16} {_duration_100ns_to_str(rec.kernel_time_100ns)}")
        if rec.user_time_100ns is not None:
            print(f"  {'UserTime':<16} {_duration_100ns_to_str(rec.user_time_100ns)}")

    if not has_times and not degraded:
        # NOT the same claim as the degraded-mode banner above: degraded
        # means ThreadInfoListStream itself is absent, but this branch
        # also fires when the stream IS present and every real entry's
        # CreateTime just happens to be zero/unset (some minidump
        # producers never populate it even though the stream exists) --
        # a neutral "not available in the captured data" is accurate in
        # both cases, whereas naming ThreadInfoListStream specifically
        # would be wrong for the "stream present, empty timestamps" one.
        print(f"\n  {DIM('[~] CreateTime/ExitTime not available in the captured ThreadInfo data.')}")

    if not has_context and records:
        # No thread's CONTEXT was captured/parsed at all -- every
        # CurrentIP line above already reads "unavailable" per-thread;
        # this is the same dump-wide neutral note has_times prints for
        # CreateTime/ExitTime, never a claim that these threads are
        # somehow clean or unexecuting.
        print(f"\n  {DIM('[~] CurrentIP not available -- no thread CONTEXT was captured/parsed.')}")

    print(f"\n{GREEN(f'[+] {len(records)} thread(s).')}")


def cmd_threads(mf) -> CommandResult:
    result = collect_threads(mf)
    render_threads_console(result.records, result.coverage)
    return result
